<a href="https://colab.research.google.com/github/amueke/Applied-Data-Visualization-with-R-and-ggplot2/blob/master/Chapter%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
x = tf.constant([1, 2, 3])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
(3,)
<dtype: 'int32'>


In [2]:
import tensorflow as tf
x = tf.Variable([1, 2, 3])
print(x)
print(x.shape)
print(x.dtype)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
(3,)
<dtype: 'int32'>


In [7]:
import tensorflow as tf
x = tf.Variable(3.6)
with tf.GradientTape() as tape:
     y=x*x
dy = tape.gradient(y, x)
print(dy)

tf.Tensor(7.2, shape=(), dtype=float32)


In [8]:
import numpy as np
polynomial = np.poly1d([1, 2, 3])
print(polynomial)

   2
1 x + 2 x + 3


In [9]:
print(polynomial(1.5))

8.25


In [10]:
N = 20 # number of samples
# Generate random samples between -10 to +10
X = np.random.uniform(-10, 10, size=(N,1))
Y = polynomial(X)

In [12]:
import tensorflow as tf
# Assume samples X and Y are prepared elsewhere
XX = np.hstack([X*X, X, np.ones_like(X)])
w = tf.Variable(tf.random.normal((3,1))) # the 3 coefficients
x = tf.constant(XX, dtype=tf.float32) # input sample
y = tf.constant(Y, dtype=tf.float32) # output sample
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)
print(w)
for _ in range(1000):
    with tf.GradientTape() as tape:
        y_pred = x @ w
        mse = tf.reduce_sum(tf.square(y - y_pred))
    grad = tape.gradient(mse, w)
    optimizer.apply_gradients([(grad, w)])
print(w)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.34049302],
       [-0.6413548 ],
       [ 0.6358653 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.0164412],
       [1.9933577],
       [1.9637996]], dtype=float32)>


In [20]:
import numpy as np
import tensorflow as tf
N = 20 # number of samples
# Generate random samples between -10 to +10
polynomial = np.poly1d([1, 2, 3])
X = np.random.uniform(-10, 10, size=(N,1))
Y = polynomial(X)
# Prepare input as an array of shape (N,3)
XX = np.hstack([X*X, X, np.ones_like(X)])
# Prepare TensorFlow objects
w = tf.Variable(tf.random.normal((3,1))) # the 3 coefficients
x = tf.constant(XX, dtype=tf.float32) # input sample
y = tf.constant(Y, dtype=tf.float32) # output sample
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.01)
print(w)
# Run optimizer
for _ in range(1000):
    with tf.GradientTape() as tape:
        y_pred = x @ w
        mse = tf.reduce_sum(tf.square(y - y_pred))
    grad = tape.gradient(mse, w)
    optimizer.apply_gradients([(grad, w)])
print(w)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.6474902],
       [0.3808592],
       [0.6274031]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.0079265],
       [1.9986746],
       [2.4602168]], dtype=float32)>


In [24]:
import tensorflow as tf
import random
A = tf.Variable(random.random())
B = tf.Variable(random.random())
C = tf.Variable(random.random())
D = tf.Variable(random.random())
# Gradient descent loop
EPOCHS = 1000
optimizer = tf.keras.optimizers.Nadam(learning_rate=0.1)
for _ in range(EPOCHS):
    with tf.GradientTape() as tape:
        y1 = A + B - 8
        y2 = C - D - 6
        y3 = A + C - 13
        y4 = B + D - 8
        sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    gradA, gradB, gradC, gradD = tape.gradient(sqerr, [A, B, C, D])
    optimizer.apply_gradients([(gradA, A), (gradB, B), (gradC, C), (gradD, D)])
print(A)
print(B)
print(C)
print(D)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.5000088>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.4999957>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=9.499989>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.4999964>
